extends SceneTree
# 验证创造模式材料库的打开、选择和关闭链路：
#   godot --headless --path <项目> --script res://tests/test_block_palette.gd

const BlockLibrary = preload("res://scripts/BlockLibrary.gd")
const GameSettings = preload("res://scripts/GameSettings.gd")

var _f := 0
var _main = null
var failed := 0

func check(cond: bool, msg: String) -> void:
	if cond:
		print("  ok   ", msg)
	else:
		failed += 1
		printerr("  FAIL ", msg)

func _process(_delta: float) -> bool:
	_f += 1
	if _f == 1:
		OS.set_environment("VC_NO_SAVE", "1")
		OS.set_environment("VC_SKIP_TITLE", "1")
		OS.set_environment("VC_SETTINGS_PATH", "user://tests/block_palette/settings.json")
		_main = load("res://scenes/Main.tscn").instantiate()
		root.add_child(_main)
	elif _f == 35:
		check(_main.lib.creative_blocks().has(BlockLibrary.COPPER_ORE), "材料库包含快捷栏外的铜矿")
		check(_main.lib.creative_blocks().has(BlockLibrary.WATER), "材料库包含水")
		check(_main.lib.creative_blocks().has(BlockLibrary.MOONSTONE_LAMP), "材料库包含月石灯")
		_main.set_palette_active(true)
		check(paused, "材料库打开后暂停世界")
		check(_main.block_palette.visible, "材料库可见")
		check(not _main.player.input_enabled, "材料库打开后禁用玩家输入")
		check(_main.block_palette._buttons.size() == _main.lib.creative_blocks().size(), "材料按钮数量匹配")
		check(_main.block_palette._tab_buttons.has("recent"), "材料库包含最近使用标签")
		check(_main.block_palette._tab_buttons.has("ores"), "材料库包含矿物分类")
		check(_main.block_palette._search_edit != null, "材料库包含搜索框")
		check(_main.block_palette._search_edit.has_focus(), "材料库打开后搜索框自动聚焦")
		check(_main.block_palette._detail_icon.texture != null, "材料库详情卡显示当前材料图标")
		check(_main.block_palette._detail_name_label.text == _main.lib.block_name(_main.player.current_block()), "材料库详情卡同步当前材料名称")
		check(_main.block_palette._detail_meta_label.text.contains("#"), "材料库详情卡显示方块编号")
		check(_main.block_palette._detail_meta_label.text.contains("/"), "材料库详情卡显示当前位置")
		check(_main.block_palette._detail_use_label.text.contains("地形"), "材料库详情卡显示当前材料用途")
		var nav_start := int(_main.block_palette._selected_id)
		check(_main.block_palette.request_move_selection(1), "材料库可用键盘请求移动选择")
		check(int(_main.block_palette._selected_id) != nav_start, "材料库移动选择会更新当前预览材料")
		check(_main.block_palette._detail_name_label.text == _main.lib.block_name(int(_main.block_palette._selected_id)), "材料库移动选择同步详情卡")
		check(_main.block_palette.request_move_selection(-1), "材料库可反向移动选择")
		check(int(_main.block_palette._selected_id) == nav_start, "材料库反向移动回到原材料")
		_send_key(KEY_RIGHT)
		check(int(_main.block_palette._selected_id) != nav_start, "材料库打开时方向键可浏览材料")
		_main.block_palette._on_search_changed("月")
		check(_main.block_palette._selected_id == BlockLibrary.MOONSTONE_LAMP, "搜索后自动预览第一个匹配材料")
		check(_main.block_palette._buttons[BlockLibrary.MOONSTONE_LAMP]["root"].visible, "搜索可显示月石灯")
		check(not _main.block_palette._buttons[BlockLibrary.COPPER_ORE]["root"].visible, "月石搜索隐藏铜矿")
		_main.block_palette._on_search_changed("铜")
		check(_main.block_palette._selected_id == BlockLibrary.COPPER_ORE, "搜索铜矿后自动预览铜矿")
		check(_main.block_palette._buttons[BlockLibrary.COPPER_ORE]["root"].visible, "搜索可显示铜矿")
		check(not _main.block_palette._buttons[BlockLibrary.GRASS]["root"].visible, "搜索会隐藏不匹配材料")
		check(not _main.block_palette._empty_label.visible, "搜索有结果时不显示空状态")
		_main.block_palette._on_search_changed("发光")
		check(_main.block_palette._buttons[BlockLibrary.LANTERN]["root"].visible and _main.block_palette._buttons[BlockLibrary.MOONSTONE_LAMP]["root"].visible, "可按发光特性搜索灯具")
		check(_main.block_palette._buttons[BlockLibrary.BLUE_CRYSTAL]["root"].visible, "可按发光特性搜索蓝晶")
		check(not _main.block_palette._buttons[BlockLibrary.GRASS]["root"].visible, "发光搜索隐藏普通地形材料")
		_main.block_palette._on_search_changed("矿物")
		check(_main.block_palette._buttons[BlockLibrary.COPPER_ORE]["root"].visible, "可按矿物分类搜索铜矿")
		check(not _main.block_palette._buttons[BlockLibrary.GRASS]["root"].visible, "矿物搜索隐藏草方块")
		_main.block_palette._on_search_changed("透明")
		check(_main.block_palette._buttons[BlockLibrary.GLASS]["root"].visible, "可按透明特性搜索玻璃")
		check(not _main.block_palette._buttons[BlockLibrary.STONE]["root"].visible, "透明搜索隐藏不透明石头")
		_main.block_palette._on_search_changed("夜景")
		check(_main.block_palette._buttons[BlockLibrary.LANTERN]["root"].visible and _main.block_palette._buttons[BlockLibrary.MOONSTONE_LAMP]["root"].visible, "可按夜景用途搜索照明材料")
		check(not _main.block_palette._buttons[BlockLibrary.DIRT]["root"].visible, "夜景搜索隐藏普通地形材料")
		_main.block_palette._on_search_changed("水景")
		check(_main.block_palette._buttons[BlockLibrary.WATER]["root"].visible and _main.block_palette._buttons[BlockLibrary.REEDS]["root"].visible, "可按水景用途搜索水和芦苇")
		check(not _main.block_palette._buttons[BlockLibrary.BRICK]["root"].visible, "水景搜索隐藏普通建筑材料")
		_main.block_palette._on_search_changed("植物")
		check(_main.block_palette._buttons[BlockLibrary.WILDFLOWER]["root"].visible and _main.block_palette._buttons[BlockLibrary.PINE_LEAVES]["root"].visible, "可按植物用途搜索植被材料")
		check(not _main.block_palette._buttons[BlockLibrary.IRON_ORE]["root"].visible, "植物搜索隐藏矿物材料")
		_main.block_palette._on_search_changed("晶洞")
		check(_main.block_palette._buttons[BlockLibrary.BLUE_CRYSTAL]["root"].visible, "可按晶洞用途搜索蓝晶")
		check(not _main.block_palette._buttons[BlockLibrary.GLASS]["root"].visible, "晶洞搜索隐藏普通透明材料")
		_main.block_palette._on_search_changed("资源")
		check(_main.block_palette._buttons[BlockLibrary.COPPER_ORE]["root"].visible and _main.block_palette._buttons[BlockLibrary.COAL_ORE]["root"].visible, "可按资源用途搜索矿物")
		check(not _main.block_palette._buttons[BlockLibrary.WILDFLOWER]["root"].visible, "资源搜索隐藏植物材料")
		_main.block_palette._on_search_changed("不存在")
		check(_main.block_palette._empty_label.visible, "搜索无结果时显示空状态")
		var selected_before_empty: int = int(_main.block_palette._selected_id)
		_main.block_palette._on_search_submitted("不存在")
		check(_main.block_palette.visible, "空搜索回车不会关闭材料库")
		check(_main.block_palette._selected_id == selected_before_empty, "空搜索回车不更改当前选择")
		_main.set_palette_active(false)
		_main.set_palette_active(true)
		check(_main.block_palette._search_text == "", "重新打开材料库会清空搜索")
		check(_main.block_palette._search_edit.has_focus(), "重新打开材料库会重新聚焦搜索框")
		check(not _main.block_palette._empty_label.visible, "重新打开材料库不保留空搜索状态")
		check(_main.block_palette._buttons[BlockLibrary.GRASS]["root"].visible, "清空搜索后恢复全部材料")
		_main.block_palette._select_category("ores")
		check(_main.block_palette._buttons[BlockLibrary.COPPER_ORE]["root"].visible, "矿物分类显示铜矿")
		check(not _main.block_palette._buttons[BlockLibrary.GRASS]["root"].visible, "矿物分类隐藏草方块")
		_main.block_palette._select_category("decor")
		check(_main.block_palette._buttons[BlockLibrary.MOONSTONE_LAMP]["root"].visible, "装饰分类显示月石灯")
		_main.block_palette._select_block(BlockLibrary.MOONSTONE_LAMP)
		check(_main.block_palette._detail_name_label.text == "月石灯", "选择月石灯后详情卡更新名称")
		check(_main.block_palette._detail_meta_label.text.contains("发光") and _main.block_palette._detail_meta_label.text.contains("#27"), "月石灯详情卡显示发光和编号")
		check(_main.block_palette._detail_use_label.text.contains("夜景") and _main.block_palette._detail_use_label.text.contains("照明"), "月石灯详情卡显示照明用途")
		_main.set_palette_active(true)
		_main.block_palette._select_category("ores")
		_main.block_palette._on_search_submitted("铜")
		check(_main.block_palette._detail_name_label.text == "铜矿", "回车选择材料后详情卡更新名称")
		check(_main.block_palette._detail_meta_label.text.contains("矿物") and _main.block_palette._detail_meta_label.text.contains("#22"), "回车选择材料后详情卡显示类别和编号")
		check(_main.block_palette._detail_use_label.text.contains("资源") and _main.block_palette._detail_use_label.text.contains("矿脉"), "铜矿详情卡显示资源用途")
		check(not paused, "搜索回车选择材料后恢复世界")
		check(not _main.block_palette.visible, "搜索回车选择材料后关闭材料库")
		check(_main.player.input_enabled, "搜索回车选择材料后恢复玩家输入")
		check(_main.player.current_block() == BlockLibrary.COPPER_ORE, "搜索回车可选择非快捷栏方块")
		_main.hud._process(0.0)
		check(_main.hud._shown_block_id == BlockLibrary.COPPER_ORE, "HUD 当前材料徽章同步非快捷栏方块")
		check(_main.hud._current_icon.texture != null, "HUD 当前材料徽章显示图标")
		check(_main.hud._recent_row.visible, "HUD 最近材料条可见")
		check(_main.hud._recent_slots.size() >= 1 and int(_main.hud._recent_slots[0]["id"]) == BlockLibrary.COPPER_ORE, "HUD 最近材料条显示刚选材料")
		check(not _main.player.recent_block_ids.is_empty() and int(_main.player.recent_block_ids[0]) == BlockLibrary.COPPER_ORE, "玩家最近材料列表已同步")
		_main.player.set_recent_blocks([BlockLibrary.COPPER_ORE, BlockLibrary.IRON_ORE])
		check(_main.player.cycle_recent(1), "可快捷轮换最近材料")
		check(_main.player.current_block() == BlockLibrary.IRON_ORE, "快捷轮换切到下一个最近材料")
		check(_main.player.cycle_recent(1), "最近材料可循环轮换")
		check(_main.player.current_block() == BlockLibrary.COPPER_ORE, "最近材料轮换回到列表开头")
		_main.player._on_key(KEY_R)
		check(_main.player.current_block() == BlockLibrary.IRON_ORE, "R 键可快捷切换最近材料")
		var saved := GameSettings.load_settings()
		var recent: Array = saved.get("recent_blocks", [])
		check(not recent.is_empty() and int(recent[0]) == BlockLibrary.COPPER_ORE, "最近使用会写入设置")
		_main.set_palette_active(true)
		_main.block_palette._select_category("recent")
		check(_main.block_palette._buttons[BlockLibrary.COPPER_ORE]["root"].visible, "最近使用显示刚选过的方块")
		check(not _main.block_palette._buttons[BlockLibrary.GRASS]["root"].visible, "最近使用隐藏未选方块")
		_main.set_palette_active(false)
		_main.player._select_slot(0)
		check(_main.player.current_block() == BlockLibrary.GRASS, "快捷栏仍可覆盖材料选择")
		_main.set_game_paused(true)
		_main.pause_menu.palette_requested.emit()
		check(paused and _main.block_palette.visible and not _main.pause_menu.visible, "暂停菜单中可打开材料库")
		var esc := InputEventKey.new()
		esc.pressed = true
		esc.keycode = KEY_ESCAPE
		_main._unhandled_input(esc)
		check(paused, "从暂停菜单打开的材料库 Esc 关闭后仍暂停")
		check(_main.pause_menu.visible, "材料库 Esc 关闭后回到暂停菜单")
		check(not _main.block_palette.visible, "材料库 Esc 关闭后面板隐藏")
		check(not _main.player.input_enabled, "材料库返回暂停菜单后玩家输入仍禁用")
		_main.pause_menu.palette_requested.emit()
		_main.block_palette._select_block(BlockLibrary.MOONSTONE_LAMP)
		check(paused and _main.pause_menu.visible, "暂停菜单中选材后回到暂停菜单")
		check(_main.player.current_block() == BlockLibrary.MOONSTONE_LAMP, "暂停菜单中选材仍会切换当前材料")
		_main.set_game_paused(false)
		if failed == 0:
			print("✅ ALL BLOCK PALETTE TESTS PASSED")
		else:
			printerr("❌ ", failed, " 个材料库测试失败")
		return true
	return false

func _send_key(keycode: int) -> void:
	var event := InputEventKey.new()
	event.pressed = true
	event.keycode = keycode
	_main._unhandled_input(event)
